application: metricas-formales 
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
# Route handlers
- url: /app
  static_dir: static 
- url: .*
  script: api.app


libraries:
- name: webapp2
  version: latest

skip_files:
 - (.*/)node_modules
 - ^(.*/)build$
 - (.*/)grunt(.*)
 - (.*/)?.*\.py[co]$
 - ^test
 - (.*/).*.md$
 - (.*/).*.coffee$
 - (.*/).*.opts$
 - (.*/).*.less$
 - (.*/).*.scss$
 - (.*/).*.Makefile$
 - (.*/).*.Makefile.1$
 - (.*/).*marked.*
 - (.*/).*.log$
 - (.*/).*.map$
 - (.*/)?\..*$
 - (.*/).*~$
 - (.*/)LICENSE
 - (.*/).*.gzip$
 - static/(.*/).*.yaml$
 - ^(.*/)?#.*#$
 - ^(.*/)?.*~$
 - ^(.*/)?.*\.py[co]$
 - ^(.*/)?.*/RCS/.*$
 - ^(.*/)?\..*$
 - static/(.*/).*.test$